### ISSUE TITLE
[Purchase] Cap nhat tu dong gia khuyen mai khi tao don hang Domestic va Oversea

### ISSUE THREAD

**Issue by trung85** [trung85/warehouse#134]
- Chỉnh sửa 2 màn hình tạo đơn hàng: Domestic và Oversea
- Tự động chọn giá khuyến mãi cho sản phẩm khi tạo đơn hàng
se can cu vao ngay shiped date -> de lay gia khuyen mai

Menu: 
<img width="851" alt="screen shot 2017-09-19 at 15 58 10" src="https://user-images.githubusercontent.com/3256362/30584694-b8b1a808-9d54-11e7-9cd9-6f3fdcaf3940.png">
Man hinh Domestic|Oversea:
<img width="1104" alt="screen shot 2017-09-19 at 15 57 47" src="https://user-images.githubusercontent.com/3256362/30584784-068dd2ea-9d55-11e7-90cc-917907dc96d4.png">

**Comment by trung85** [comment]
![diagram_purchase_order](https://user-images.githubusercontent.com/3256362/30587661-2741f44a-9d5e-11e7-9bd8-503074a7ec41.png)

**Comment by datnhvn** [comment]
Fix issues:
1	them cot promotionPrice trong bang detail_order_nn																	
2	khi cap nhat don hang : cho phep tu dong thay doi gia, khi chon supplier , delivery date																	
3	khi nao cancel thi chon lai order moi nhat -> turong hop new																	
4						truong hop update thi lay cai update												
5	domestic, oversea orders																	
6	bo field Discount 																	
7	trường hợp cấu hình sp có thể áp dụng 2 CTKM -> thì chọn áp dụng CTKM đầu tiên
8      To mau cho nhung sp co khuyen mai

https://docs.google.com/spreadsheets/d/1NqQdcwtf4ZC2eJREb5ACXcHhNLho6QZxg701iERnxqM/edit#gid=0
