### ISSUE TITLE
[BC Purchase] Báo cáo số lượng hàng khuyến mãi, giảm giá theo tháng

### ISSUE THREAD

**Issue by trung85** [trung85/warehouse#157]
- template link :
https://docs.google.com/spreadsheets/d/1GCVk2Rm68ng02eak3Ph0tL92FNZr3groqAVtJRnmVP0/edit#gid=980618190
- Chỉ lấy những sản phẩm có áp dụng khuyến mãi

**Comment by trung85** [comment]
```
Sua cac issue kem theo link : https://docs.google.com/spreadsheets/d/1NqQdcwtf4ZC2eJREb5ACXcHhNLho6QZxg701iERnxqM/edit#gid=1242797304 (sheet issue #157)
cai tien toc do, remove code du thua
```

**Comment by datnhvn** [comment]
More issues:

1. Check duplicate code before add new data for screens:
  - FormStockInputEditor.cs
  - FormStockOutputEditor.cs
  - FormInputSheet.cs
  - FormDomesticOrder.cs
  - FormOrderOversea.cs

2. Remove/Upgrade functions
  - SupplierRepository.cs (query from cache)
  + List<Supplier> selectAllSuppliers() 
  + List<SupplierExtend> selectSuppliers(SupplierExtend param) 
  + List<Supplier> selectByType(string type)
  + Supplier selectById(string supplierId)

3. Reports:
  - Optimize all report's queries which using template WHERE SUPPLIERID IN (.......)
