### ISSUE TITLE
[PO] Tạo script import dữ liệu củ thông tin phiếu nhập sang InputSheet, InputSheetItem

### ISSUE THREAD

**Issue by trung85** [trung85/warehouse#163]
- Import dữ liệu nhập hàng củ sang InputSheet, InputSheetItem
map data link : https://docs.google.com/spreadsheets/d/1NqQdcwtf4ZC2eJREb5ACXcHhNLho6QZxg701iERnxqM/edit#gid=1390394751
- Cập nhật lại ORDER_NHANH_NHANH.num_input : tổng số phiếu nhập của từng order
- Cập nhật lại trạng thái ORDER_NHANH_NHANH.InputSheetStatus : nhập hết sp hay chưa 
- Cập nhật lại tổng nhập hiện tại DETAIL_ORDER_NN.QtyInputted : số lượng đã nhập tính đến thời điểm hiện tại

db structure:
<img width="1138" alt="screen shot 2017-12-29 at 11 36 56" src="https://user-images.githubusercontent.com/3256362/34429580-9f9bccd6-ec8c-11e7-9164-8aae32d99086.png">

**Comment by trung85** [comment]
script 01: 

```sql
-- insert du lieu vao InputSheet, voi InputNumber mac dinh la 0
INSERT INTO test_input_number (DimMonth, InputNumber, InputSheetCode)
SELECT 
	CAST(LEFT(CONVERT(varchar, INPUT_SHEET_D_DATE,112),6) as int),
	0,
	[INPUT_SHEET_D_ID]
FROM [Nhanh_Nhanh_phase1].dbo.INPUT_SHEET_DOMESTIC
where year(INPUT_SHEET_D_DATE) = 2016
order by INPUT_SHEET_D_DATE, INPUT_SHEET_D_ID

-- cap nhat lai InputNumber dung partition by
SELECT 
   Id, 
   DimMonth,
   ROW_NUMBER() OVER (PARTITION BY DimMonth ORDER By Id) as ROW,
   InputSheetCode
FROM test_input_number
```

https://stackoverflow.com/questions/2334712/how-do-i-update-from-a-select-in-sql-server

**Comment by trung85** [comment]
script 02:

```sql
-- insert du lieu input chi tiet tu DETAIL_INPIUT_DOMESTIC, DETAIL_INPUT_OVERSEA
INSERT INTO test_input_number_detail (InputSheetId, ItemId, InputQty)
SELECT 
	masterDomestic.Id as InputSheetId
	,detailDomestic.ITEM_ID ItemId
	,detailDomestic.QUANTITY_INPUT_D InputQty
FROM [Nhanh_Nhanh_phase1].dbo.DETAIL_INPUT_SHEET_DOMESTIC detailDomestic
INNER JOIN test_input_number masterDomestic
	ON detailDomestic.INPUT_SHEET_D_ID = masterDomestic.InputSheetCode
order by masterDomestic.InputSheetCode
```

**Comment by trung85** [comment]
script 03: 

```sql
-- cap nhat tong so luong nhap cho chi tiet don hang QtyInputted
UPDATE
    Table_A
SET
    Table_A.QtyInputted = detail_inputed.TotalQty
FROM
    DETAIL_ORDER_NN AS Table_A
INNER JOIN (
	SELECT masterIS.OrderId, detailIS.ItemId, SUM(detailIS.InputQty) TotalQty
	FROM InputSheetItem detailIS
	LEFT JOIN InputSheet masterIS ON detailIS.InputSheetId = masterIS.Id
	GROUP BY masterIS.OrderId, detailIS.ItemId
) as detail_inputed
on Table_A.ORDERID_NN = detail_inputed.OrderId and Table_A.ITEM_ID = detail_inputed.ItemId
```

**Comment by trung85** [comment]
scrip 04: 
```sql
-- cap nhat tong so phieu nhap cho don hang
-- lam giong script 03
```

**Comment by trung85** [comment]
script 05 : 
```sql
-- mac dinh InputSheetStatus = 1 -> da xuat het
update ORDER_NHANH_NHANH set InputSheetStatus = 1

-- chon nhung order id nao ma co order qty != inputed qty
-- cap nhat lai trang thai InputSheetStatus = 0
UPDATE
    Table_A
SET
    Table_A.InputSheetStatus = 0
FROM
    ORDER_NHANH_NHANH AS Table_A
INNER JOIN (
	SELECT distinct ORDERID_NN orderid
	FROM DETAIL_ORDER_NN
	WHERE QUANTITY_NN != QtyInputted  --- chua nhap het so luong
) orders__not_input
on Table_A.ORDERID_NN = orders__not_input.orderid
```

**Comment by datnhvn** [comment]
--==============================================================================
--Migrate data from INPUT_SHEET_DOMESTIC, INPUT_SHEET_OVERSEA into InputSheet
--==============================================================================
--delete all draft data from table InputSheet
DELETE FROM InputSheet;
--reset identity
DBCC CHECKIDENT ('[InputSheet]', RESEED, 0)
GO

INSERT INTO InputSheet(InputSheetCode
      ,OrderId
      ,InventoryName
      ,InputDate
      ,DiliverName
      ,ReceiverName
      ,Note
      ,InputType   
      ,DimMonthInputNumber
      ,InputNumber
      ,CreatedDate
      ,CreatedBy
      ,UpdatedDate
      ,UpdatedBy)
--select all masters from domestic and oversea and sort by InputDate
SELECT * 
FROM (
	SELECT [INPUT_SHEET_D_ID] InputSheetCode
	  ,[ORDERID_NN] OrderId
	  ,[INVENTORY_NAME_TD] InventoryName
	  ,[INPUT_SHEET_D_DATE] InputDate
	  ,[DELIVERER_NAME_SD] DiliverName
	  ,[RECEIVER_D_NAME] ReceiverName
	  ,[NOTE_INPUT_SHEET_D] Note
	  ,'domestic' InputType
	  ,CAST(LEFT(CONVERT(varchar, INPUT_SHEET_D_DATE,112),6) as int) DimMonthInputNumber
	  ,0 InputNumber
	  ,[INPUT_SHEET_D_DATE] CreatedDate
	  ,1 CreatedBy
	  ,[INPUT_SHEET_D_DATE] UpdatedDate
	  ,1 UpdatedBy
	FROM [INPUT_SHEET_DOMESTIC] inputSheetDomestic
	UNION
	SELECT [INPUT_SHEET_F_ID] InputSheetCode
	  ,[ORDERID_NN] OrderId
	  ,[INVENTORY_NAME_DG] InventoryName
	  ,[INPUT_SHEET_F_DATE] InputDate
	  ,[DELIVERER_NAME_SO] DiliverName
	  ,[RECEIVER_F_NAME] ReceiverName
	  ,[NOTE_INPUT_SHEET_0] Note
	  ,'oversea' InputType
	  ,CAST(LEFT(CONVERT(varchar, INPUT_SHEET_F_DATE,112),6) as int) DimMonthInputNumber
	  ,0 InputNumber
	  ,[INPUT_SHEET_F_DATE] CreatedDate
	  ,1 CreatedBy
	  ,[INPUT_SHEET_F_DATE] UpdatedDate
	  ,1 UpdatedBy
	FROM [INPUT_SHEET_OVERSEA]
) InputSheetMaster
ORDER BY InputSheetMaster.InputDate

--Generate and update InputNumber
;MERGE INTO InputSheet inputSheet
	USING (
		SELECT Id, 
		ROW_NUMBER() OVER (PARTITION BY DimMonthInputNumber ORDER By Id) as InputNumber
        FROM InputSheet
    ) S
	ON inputSheet.Id = S.Id
WHEN MATCHED THEN
   UPDATE SET InputNumber = S.InputNumber;

--=============================================================================================
--Migrate data from DETAIL_INPUT_SHEET_DOMESTIC, DETAIL_INPUT_SHEET_OVERSEA into InputSheetItem
--=============================================================================================
--delete all draft data from table InputSheetItem
DELETE FROM InputSheetItem;
--reset identity
DBCC CHECKIDENT ('[InputSheetItem]', RESEED, 0)
GO

INSERT INTO InputSheetItem(InputSheetId
	, ItemId
	, InputQty)
--select all details from domestic and oversea and sort by InputDate
SELECT * 
FROM (
	SELECT inputSheet.Id InputSheetId
	,detailDomestic.ITEM_ID ItemId
	,detailDomestic.QUANTITY_INPUT_D InputQty
	FROM DETAIL_INPUT_SHEET_DOMESTIC detailDomestic
	INNER JOIN InputSheet inputSheet ON detailDomestic.INPUT_SHEET_D_ID = inputSheet.InputSheetCode
	UNION
	SELECT inputSheet.Id InputSheetId
	,detailOversea.ITEM_ID ItemId
	,detailOversea.QUANTITY_INPUT_F InputQty
	FROM DETAIL_INPUT_SHEET_OVERSEA detailOversea
	INNER JOIN InputSheet inputSheet ON detailOversea.INPUT_SHEET_F_ID = inputSheet.InputSheetCode
) InputSheetDetail

--=============================================================================================
--Update DETAIL_ORDER_NN.QtyInputted
--=============================================================================================
UPDATE
    DETAIL_ORDER_NN
SET
    QtyInputted = detailInputed.TotalQty
FROM
    DETAIL_ORDER_NN AS orderDetail
	INNER JOIN (
		SELECT masterIS.OrderId, detailIS.ItemId, SUM(detailIS.InputQty) TotalQty
		FROM InputSheetItem detailIS
		LEFT JOIN InputSheet masterIS ON detailIS.InputSheetId = masterIS.Id
		GROUP BY masterIS.OrderId, detailIS.ItemId
	) as detailInputed
	ON orderDetail.ORDERID_NN = detailInputed.OrderId and orderDetail.ITEM_ID = detailInputed.ItemId

--=============================================================================================
--Update ORDER_NHANH_NHANH.num_input
--=============================================================================================
UPDATE
    ORDER_NHANH_NHANH
SET
    num_input = inputSheetNum.InputNumber
FROM
    DETAIL_ORDER_NN AS orderDetail
	INNER JOIN (
		SELECT OrderId, COUNT(Id) InputNumber 
		FROM InputSheet
		GROUP BY OrderId
	) as inputSheetNum
	ON orderDetail.ORDERID_NN = inputSheetNum.OrderId

--=============================================================================================
--Update ORDER_NHANH_NHANH.InputSheetStatus
--=============================================================================================
-- mac dinh InputSheetStatus = 1 -> da xuat het
UPDATE ORDER_NHANH_NHANH set InputSheetStatus = 1
-- chon nhung order id nao ma co order qty != inputed qty
-- cap nhat lai trang thai InputSheetStatus = 0
UPDATE
    Table_A
SET
    Table_A.InputSheetStatus = 0
FROM
    ORDER_NHANH_NHANH AS Table_A
INNER JOIN (
	SELECT distinct ORDERID_NN orderid
	FROM DETAIL_ORDER_NN
	WHERE QUANTITY_NN != QtyInputted  --- chua nhap het so luong
) orders__not_input
on Table_A.ORDERID_NN = orders__not_input.orderid
