### ISSUE TITLE
[Stock] Quản lí thông tin mở rộng cho sản phẩm

### ISSUE THREAD

**Issue by trung85** [trung85/warehouse#168]
- design link : https://www.draw.io/#G1Sw-Vn0IluPqNgBNmB0lAY9Z1KMnn7pYu 
- sheet name : "issue #168"
- create 3 new tables

![screen shot 2018-01-05 at 17 45 30](https://user-images.githubusercontent.com/3256362/34605993-421d6966-f240-11e7-8799-4cddfb056ac1.png)

**Comment by datnhvn** [comment]
Fix bugs: (done)
1. Right click -> add menu refresh
2. Input invalid value into combobox on grid -> exception
3. Copy and past a valid value into combobox on grid -> exception
4. Open the sort feature by columns

Branch:
https://github.com/datnhvn/warehouse/tree/feature/168-sua-vai-bug-lien-quan
