### ISSUE TITLE
[Purchase] Quản lí tình trạng mua hàng theo nhà cung cấp

### ISSUE THREAD

**Issue by trung85** [trung85/warehouse#173]
- xác định các đơn hàng chưa nhập, hiển thị thông tin sản phẩm chưa nhập / đã nhập
- hiển thị chi tiết các phiếu nhập của đơn hàng
- cho phép nhập hàng sau khi chọn sản phẩm chưa nhập

thiet ke man hinh: https://www.draw.io/#G1Sw-Vn0IluPqNgBNmB0lAY9Z1KMnn7pYu 
cải tiến màn hình danh sách Domestic Order, Oversea Order

branch : upstream/feature/173-quan-li-tinh-trang-mua-hang-nha-cung-cap

**Comment by datnhvn** [comment]
29/1/2018
Fix some issues:

1.Export: 
  - wrap text (Item name, code 1 2 3), (DONE)
  - End row: font size 9 -> 8 (DONE)
  - Export (add exit button on dialog) (DONE)
2.Input Sheet editer: 
  - Inputed Date: Dilivery Date (Not order Date)   (NOT FOUND)
  - Cho phep edit input number : NK001
  - Button Cancel -> data didn't reset if add new items from list orders (DONE)
3.Grid input detail
  - UTF-8
  - Promotion item: set Order Qty = 0 (DONE)
  - Export menu Inputs: (add input date)   (DONE)
    PO - NK01 - 22/01/2018
    PO - NK02 - 23/02/2018
  - San  pham chua nhap het: hien thi them so luong con lai tren grid (DONE)
  - decrease grid (DONE)
4.Grid order
  - increase button high (DONE)

**Comment by datnhvn** [comment]
29/1/2018
Work for  some additional requests:
1.Design lai form report filter (chia groups thanh columns)   (DONE)
2.Form report filter: loc theo supplierId -> doi thanh loc theo mã liên kết kế toán (ap dung cho tat ca cac reports trong form)   (DONE)
3.bo cac logo trong cac report, khi nao can se them vao theo cach moi   (DONE)
4.bao cao hang chua nhap ItemNotInputed chua dong tong cong "cot con lai" (DONE)
5.bao cao tong hop hang mua PurchaseSummary chua co dong tong cong "cot tong cong" (DONE)
  - title dang bi sai: BÁO CÁO TỔNG HỢP HÀNG MUA TỪ 30/01/2018 ĐẾN 31/01/2018
  - doi thanh: BÁO CÁO TỔNG HỢP HÀNG NHẬP TỪ 30/01/2018 ĐẾN 31/01/2018
6.bao cao nhap hang OrderInput chua export hang khuyen mai neu co trong phieu nhap (DONE)
  - title dang bi sai: BÁO CÁO CHI TIẾT HÀNG MUA TỪ 30/01/2018 ĐẾN 31/01/2018
  - doi thanh: BÁO CÁO CHI TIẾT NHẬP HÀNG TỪ 30/01/2018 ĐẾN 31/01/2018
7.Them button export PO trong man hinh InputSheet editor va xu ly export (DONE)
