### ISSUE TITLE
[BC Purchase] Báo cáo tổng hợp hàng mua theo tháng, nhiều tháng

### ISSUE THREAD

**Issue by trung85** [trung85/warehouse#176]
link : https://docs.google.com/spreadsheets/d/1GCVk2Rm68ng02eak3Ph0tL92FNZr3groqAVtJRnmVP0/edit#gid=1626170416 

branch: upstream/feature/176-bao-cao-tong-hop-hang-mua-nha-cung-cap

**Comment by trung85** [comment]
- su dung ma lien ket ke toan trong tat ca cac bao cao
- import/export danh sach hang khuyen mai cung dung ma lien ket ke toan
- sap xep lai thu tu cac cot trong cac report : theo thu tu: so don hang, ma nha cung cap, ten nha cung cap, ma san pham, ten san pham
- chinh lai cai textbox cua man hinh filter , co the copy paste danh sach ma ko xuat hien dau gach

**Comment by datnhvn** [comment]
1. Cập nhật lại màn hình "Quản lý mã liên kết kết toán"
   - AccountantCode : not null
   - Không cho phép duplicate AccountantCode
2. import danh sach hang khuyen mai cung dung ma lien ket ke toan
   - Update Mã nhà cung cấp thành Mã liên kết kế toán
   - AccountantCode -> find supplier

**Comment by datnhvn** [comment]
UPDATE SUPPLIERS
SET ACCOUNTANT_CODE = LEFT(SUPPLIERID, 2) + CONVERT(varchar(10), CONVERT(INT, RIGHT(SUPPLIERID, 10)))
