### ISSUE TITLE
[Stock] Thiết lập nhân viên thuôc quản lí KHO, thêm field IsStockKeeper

### ISSUE THREAD

**Issue by trung85** [trung85/warehouse#219]
- them cot luu tru phan loai nhan vien thuoc bo phan kho, bang EMPLOYEES

- sua lai man hinh "QL Thong tin mo rong san pham", load lai thong tin nhan vien co IsStockKeeper = 1
<img width="865" alt="screen shot 2018-04-08 at 2 34 29 pm" src="https://user-images.githubusercontent.com/3256362/38464591-76450cb0-3b3a-11e8-8861-38c021d9dc08.png">

**Comment by datnhvn** [comment]
EMPLOYEES.IsStockKeeper (new field)
