### ISSUE TITLE
Import/Export danh sách khuyến mãi sản phẩm thuộc nhà cung cấp

### ISSUE THREAD

**Issue by trung85** [trung85/warehouse#93]

**Comment by datnhvn** [comment]
[SupplierPromotions_Import_validation_errors.xlsx](https://github.com/trung85/warehouse/files/1603566/SupplierPromotions_Import_validation_errors.xlsx)
[SupplierPromotions_Import_validation_ok_1.xlsx](https://github.com/trung85/warehouse/files/1603567/SupplierPromotions_Import_validation_ok_1.xlsx)
[SupplierPromotions_Import_validation_ok_2.xlsx](https://github.com/trung85/warehouse/files/1603568/SupplierPromotions_Import_validation_ok_2.xlsx)

**Comment by datnhvn** [comment]
2018/1/17
1. Cập nhật lại màn hình "Quản lý mã liên kết kết toán"
   - AccountantCode : not null
   - Không cho phép duplicate AccountantCode
2. import danh sach hang khuyen mai cung dung ma lien ket ke toan
   - Update Mã nhà cung cấp thành Mã liên kết kế toán
   - AccountantCode -> find supplier

Fix in issue:
https://github.com/trung85/warehouse/issues/176
